# Site setings
name: 'Chidera Bisong'
description: 'GIS - Remote Sensing - Geospatial Data Analysis'
meta_description: 'GIS, remote sensing, geospatial data analysis.'
logo:
# Author image is used in site sidebar and greetings in the home page hero text
author:
  image: 'profile.png'
  greetings: "Hi there! My name is Chidera Bisong. I am a GIS/ Geospatial Data Analyst at Integrated Ecodev Systems Konsult (IESK). I am currently undertaking a Masters Degree in Geographic Information Systems and Remote Sensing at Charles Sturt University in Australia."
favicon: ''
baseurl: 
production_url: 
disqus: ''
mailchimp_url: ''
# Add your GA Tracking Id
ga_analytics: 

# Contact form setings
email: chidera.bisong@ecodevkonsult.com 
contact_page_description: ""
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
# twitter: ''
# facebook: ''
github: 'cbisong'
# codepen: ''
# dribbble: ''
# medium: ''
# instagram: ''
# pinterest: ''
linkedin: 'chiderabisong'
# producthunt: ''
# quora: ''

# Navigation
navigation:
  - text: Home
    url: /
  - text: About
    url: /about
  # - text: Style Guide
  #   url: /style-guide
  - text: Contact Me
    url: /contact
  # - text: Search
  #   url: /search

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
